[{"id": 6074, "name": "89", "raw": "2023-07-28 08:44:42,028 | Failed at Play [3_nvme_vhba_device_ops] ********************\n2023-07-28 08:44:42,028 | TASK [3_nvme_vhba_device_ops][Run iozone test on new added disk nvd0] \ntask path: /home/worker/workspace/Ansible_FreeBSD_13.x_32bit_MAIN_SATA_E1000E_BIOS/ansible-vsphere-gos-validation/linux/vhba_hot_add_remove/test_disk_io.yml:24\nfatal: [localhost -> 10.218.129.205]: FAILED! => non-zero return code\nerror message:\nnon-zero return code: 1\nShared connection to 10.218.129.205 closed.\n>>>>>>>>>>>>>Start to test /dev/nvd0<<<<<<<<<<<<<<<<<<\nCreate mount point /mnt/nvd0p1\nExecute command: mkdir -p /mnt/nvd0p1\nReturn Code: 0\nExecute command: mount  /dev/nvd0p1 /mnt/nvd0p1 >/dev/null 2>&1\nReturn Code: 0\nMount /dev/nvd0p1 to /mnt/nvd0p1: SUCCEED\nCreate folder /mnt/nvd0p1/testdir:  Execute command: mkdir /mnt/nvd0p1/testdir\n/mnt/nvd0p1: create/symlink failed, no inodes free\nmkdir: /mnt/nvd0p1/testdir: No space left on device\nReturn Code: 1\nFAIL", "category": null, "processed": "timestamp failed at play number nvme v hba device ops timestamp task number nvme v hba device ops run io zone test on new added disk nvd number task path home worker workspace ansible freebsd number x number b it main sata bios ansible vsphere gos validation linux v hba hot add remove test disk io yml number fatal localhost ip address failed nonzero return code error message nonzero return code number shared connection to ip address closed start to test dev nvd number create mount point mount nvd number p number execute command mkdir p mount nvd number p number return code number execute command mount dev mount dev null number return code number mount dev to mount succeed create folder mount test directory execute command mkdir mount test directory mount create symlink failed no i nodes free mkdir mount test directory no space left on device return code number fail", "solution": "deepdive", "target": "targetvm", "version": 202308030456}, {"id": 6075, "name": "89", "raw": "2023-08-01 03:09:32,001 | Failed at Play [1_sata_vhba_device_ops] ********************\n2023-08-01 03:09:32,001 | TASK [1_sata_vhba_device_ops][Restart OS using win_reboot module] \ntask path: /home/worker/workspace/Ansible_Windows_11_70GA_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/windows/utils/win_shutdown_restart.yml:23\nTimeoutError: timed out\nThe above exception was the direct cause of the following exception:\nurllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f0a30624ee0>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)')\nThe above exception was the direct cause of the following exception:\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0a30624ee0>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0a30624ee0>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nansible.errors.AnsibleError: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f0a30624ee0>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nException: Timed out waiting for last boot time check (timeout=600.0)\nfatal: [localhost -> 10.168.211.149]: FAILED! => Timed out waiting for last boot time check (timeout=600.0)\nerror message:\nTimed out waiting for last boot time check (timeout=600.0)", "category": null, "processed": "timestamp failed at play number sata v hba device ops timestamp task number sata v hba device ops restart os using win reboot module task path home worker workspace ansible windows number ga lsi logic sas efi ansible vsphere gos validation windows utilities win shutdown restart yml number timeout error timed out the above exception was the direct cause of the following exception url library number exceptions connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number the above exception was the direct cause of the following exception url library number exceptions max retry error https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number requests exceptions connect timeout https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number ansible errors ansible error https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number exception timed out waiting for last boot time check timeout number fatal localhost ip address failed timed out waiting for last boot time check timeout number error message timed out waiting for last boot time check timeout number", "solution": "retry", "target": "targetvm", "version": 202308030456}, {"id": 6076, "name": "89", "raw": "2023-07-17 06:09:53,017 | Failed at Play [01_deploy_vm] ******************************\n2023-07-17 06:09:53,017 | TASK [01_deploy_vm][Check VM 'test_vm' IP address] *********\ntask path: /home/worker/workspace/Ansible_Windows_Server_LTSC_70GA_SATA_VMXNET3_BIOS/ansible-vsphere-gos-validation/common/vm_get_ip.yml:48\nfatal: [localhost]: FAILED! => Failed to get VM 'test_vm' IP Address\nerror message:\nFailed to get VM 'test_vm' IP Address\n2023-07-17 06:10:29,017 | TASK [01_deploy_vm][Testing exit due to failure] ***********\ntask path: /home/worker/workspace/Ansible_Windows_Server_LTSC_70GA_SATA_VMXNET3_BIOS/ansible-vsphere-gos-validation/common/test_rescue.yml:86\nfatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_bios_sata_vmxnet3\nerror message:\nExit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_bios_sata_vmxnet3", "category": null, "processed": "timestamp failed at play number deploy vm timestamp task number deploy vm check vm test vm ip address task path home worker workspace ansible windows server lts c number ga sata vmxnet number bios ansible vsphere gos validation common vm get ip yml number fatal localhost failed failed to get vm test vm ip address error message failed to get vm test vm ip address timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c number ga sata vmxnet number bios ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm bios sata vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm bios sata vmxnet number", "solution": "retry", "target": "nimbus", "version": 202308030456}, {"id": 6077, "name": "89", "raw": "2023-07-26 07:23:17,026 | Failed at Play [01_wintools_complete_install_verify] *******\n2023-07-26 07:23:17,026 | TASK [01_wintools_complete_install_verify][Test tools failure] \ntask path: /home/worker/workspace/Ansible_Windows_11_Physical_VBS_70U3_PARAVIRTUAL_VMXNET3_EFI/ansible-vsphere-gos-validation/windows/wintools_complete_install_verify/wintools_complete_install_verify.yml:28\nfatal: [localhost]: FAILED! => VMware Tools installation failed\nerror message:\nVMware Tools installation failed\n2023-07-26 07:25:03,026 | TASK [01_wintools_complete_install_verify][Testing exit due to failure] \ntask path: /home/worker/workspace/Ansible_Windows_11_Physical_VBS_70U3_PARAVIRTUAL_VMXNET3_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86\nfatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case wintools_complete_install_verify\nerror message:\nExit testing because 'exit_testing_when_fail' is set to True in test case wintools_complete_install_verify", "category": null, "processed": "timestamp failed at play number win tools complete install verify timestamp task number win tools complete install verify test tools failure task path home worker workspace ansible windows number physical vbs para virtual vmxnet number efi ansible vsphere gos validation windows win tools complete install verify win tools complete install verify yml number fatal localhost failed vmware tools installation failed error message vmware tools installation failed timestamp task number win tools complete install verify testing exit due to failure task path home worker workspace ansible windows number physical vbs para virtual vmxnet number efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case win tools complete install verify error message exit testing because exit testing when fail is set to true in test case win tools complete install verify", "solution": "deepdive", "target": "targetvm", "version": 202308030456}, {"id": 6081, "name": "89", "raw": "2023-08-01 02:30:46,001 | Failed at Play [01_deploy_vm] ******************************\n2023-08-01 02:30:46,001 | TASK [01_deploy_vm][Check VMware Tools is running and collects guest IPv4 address successfully] \ntask path: /home/worker/workspace/Ansible_Flatcar_80GA/ansible-vsphere-gos-validation/common/vm_wait_guest_ip.yml:49\nfatal: [localhost]: FAILED! => [\"It's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.\", \"VMware Tools running status is 'guestToolsRunning'.\", \"VM's IP address in guest info is '2620:124:6020:c302:250:56ff:fea3:c0b5'.\", \"VM's all IP addresses in guest info are '['2620:124:6020:c302:250:56ff:fea3:c0b5', 'fe80::250:56ff:fea3:c0b5']'.\"]\nerror message:\nIt's timed out for VMware Tools collecting guest IPv4 address in 300 seconds.\nVMware Tools running status is 'guestToolsRunning'.\nVM's IP address in guest info is '2620:124:6020:c302:250:56ff:fea3:c0b5'.\nVM's all IP addresses in guest info are '['2620:124:6020:c302:250:56ff:fea3:c0b5', 'fe80::250:56ff:fea3:c0b5']'.\n2023-08-01 02:31:04,001 | TASK [01_deploy_vm][Testing exit due to failure] ***********\ntask path: /home/worker/workspace/Ansible_Flatcar_80GA/ansible-vsphere-gos-validation/common/test_rescue.yml:86\nfatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_ova\nerror message:\nExit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_ova", "category": null, "processed": "timestamp failed at play number deploy vm timestamp task number deploy vm check vmware tools is running and collects guest ip v number address successfully task path home worker workspace ansible flatcar number ga ansible vsphere gos validation common vm wait guest ip yml number fatal localhost failed it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address error message it s timed out for vmware tools collecting guest ip v number address in number seconds vmware tools running status is guest tools running vm sip address in guest info is ip address vm s all ip addresses in guest info are ip address ip address timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible flatcar number ga ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm ova error message exit testing because exit testing when fail is set to true in test case deploy vm ova", "solution": "retry", "target": "nimbus", "version": 202308030456}, {"id": 6078, "name": "89", "raw": "2023-07-27 12:00:09,027 | Failed at Play [01_deploy_vm] ******************************\n2023-07-27 12:00:09,027 | TASK [01_deploy_vm][Guest OS connection failure] ***********\ntask path: /home/worker/workspace/Ansible_Windows_Server_LTSC_MAIN_LSILOGICSAS_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26\nfatal: [localhost]: FAILED! => Guest winrm is not connectable in 1800 seconds.\nerror message:\nGuest winrm is not connectable in 1800 seconds.\n2023-07-27 12:00:49,027 | TASK [01_deploy_vm][Testing exit due to failure] ***********\ntask path: /home/worker/workspace/Ansible_Windows_Server_LTSC_MAIN_LSILOGICSAS_VMXNET3_EFI_HW17/ansible-vsphere-gos-validation/common/test_rescue.yml:86\nfatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_lsilogicsas_vmxnet3\nerror message:\nExit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_lsilogicsas_vmxnet3", "category": null, "processed": "timestamp failed at play number deploy vm timestamp task number deploy vm guest os connection failure task path home worker workspace ansible windows server lts c main lsi logic sas vmxnet number efi ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows server lts c main lsi logic sas vmxnet number efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi lsi logic sas vmxnet number error message exit testing because exit testing when fail is set to true in test case deploy vm efi lsi logic sas vmxnet number", "solution": "retry", "target": "testbed", "version": 202308030456}, {"id": 6082, "name": "89", "raw": "2023-07-31 07:08:23,031 | Failed at Play [15_nvdimm_cold_add_remove] *****************\n2023-07-31 07:08:23,031 | TASK [15_nvdimm_cold_add_remove][Restart OS using win_reboot module] \ntask path: /home/worker/workspace/Ansible_Windows_11_70GA_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/windows/utils/win_shutdown_restart.yml:23\nTimeoutError: timed out\nThe above exception was the direct cause of the following exception:\nurllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f4022dcc370>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)')\nThe above exception was the direct cause of the following exception:\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4022dcc370>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4022dcc370>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nansible.errors.AnsibleError: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f4022dcc370>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nException: Timed out waiting for last boot time check (timeout=600.0)\nfatal: [localhost -> 10.168.211.149]: FAILED! => Timed out waiting for last boot time check (timeout=600.0)\nerror message:\nTimed out waiting for last boot time check (timeout=600.0)", "category": null, "processed": "timestamp failed at play number nvdimm cold add remove timestamp task number nvdimm cold add remove restart os using win reboot module task path home worker workspace ansible windows number ga lsi logic sas efi ansible vsphere gos validation windows utilities win shutdown restart yml number timeout error timed out the above exception was the direct cause of the following exception url library number exceptions connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number the above exception was the direct cause of the following exception url library number exceptions max retry error https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number requests exceptions connect timeout https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number ansible errors ansible error https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number exception timed out waiting for last boot time check timeout number fatal localhost ip address failed timed out waiting for last boot time check timeout number error message timed out waiting for last boot time check timeout number", "solution": "retry", "target": "targetvm", "version": 202308030456}, {"id": 6079, "name": "89", "raw": "2023-08-02 16:02:13,002 | Failed at Play [19_pvrdma_network_device_ops] **************\n2023-08-02 16:02:13,002 | TASK [19_pvrdma_network_device_ops][Check RDMA ping result from client VM to server VM] \ntask path: /home/worker/workspace/Ansible_BCLinux_8.x_MAIN_NVME_E1000E_EFI/ansible-vsphere-gos-validation/linux/network_device_ops/pvrdma_network_device_ops.yml:161\nfatal: [localhost]: FAILED! => Failed to run RDMA ping from client VM 'test_vm_client_20230802155355' to server VM 'test_vm'. Hit error 'rdma_create_qp: Cannot allocate memory\nsetup_qp failed: -1'\nerror message:\nFailed to run RDMA ping from client VM 'test_vm_client_20230802155355' to server VM 'test_vm'. Hit error 'rdma_create_qp: Cannot allocate memory\nsetup_qp failed: -1'", "category": null, "processed": "timestamp failed at play number pvrdma network device ops timestamp task number pvrdma network device ops check remote direct memory access ping result from client vm to server vm task path home worker workspace ansible bc linux number x main nvme efi ansible vsphere gos validation linux network device ops pvrdma network device ops yml number fatal localhost failed failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error remote direct memory access create qp can not allocate memory setup qp failed number error message failed to run remote direct memory access ping from client vm test vm client timestamp to server vm test vm hit error remote direct memory access create qp can not allocate memory setup qp failed number", "solution": "deepdive", "target": "targetvm", "version": 202308030456}, {"id": 6083, "name": "89", "raw": "2023-07-28 18:10:06,028 | Failed at Play [14_lsilogic_vhba_device_ops] ***************\n2023-07-28 18:10:06,028 | TASK [14_lsilogic_vhba_device_ops][Run iozone test on new added disk da0] \ntask path: /home/worker/workspace/Ansible_FreeBSD_13.x_32bit_MAIN_SATA_E1000E_BIOS/ansible-vsphere-gos-validation/linux/vhba_hot_add_remove/test_disk_io.yml:24\nfatal: [localhost -> 10.78.225.14]: FAILED! => non-zero return code\nerror message:\nnon-zero return code: 1\nWarning: Permanently added '10.78.225.14' (ED25519) to the list of known hosts.\nShared connection to 10.78.225.14 closed.\n>>>>>>>>>>>>>Start to test /dev/da0<<<<<<<<<<<<<<<<<<\nExecute command: mount  /dev/da0p1 /mnt/da0p1 >/dev/null 2>&1\nReturn Code: 1\nMount /dev/da0p1 to /mnt/da0p1: FAIL\nFAIL\nCould not mount /dev/da0p1 to /mnt/da0p1", "category": null, "processed": "timestamp failed at play number lsi logic v hba device ops timestamp task number lsi logic v hba device ops run io zone test on new added disk da number task path home worker workspace ansible freebsd number x number b it main sata bios ansible vsphere gos validation linux v hba hot add remove test disk io yml number fatal localhost ip address failed nonzero return code error message nonzero return code number warning permanently added ip address to the list of known hosts shared connection to ip address closed start to test dev da number execute command mount dev mount dev null number return code number mount dev to mount fail fail could not mount dev to mount da number p number", "solution": "deepdive", "target": "targetvm", "version": 202308030456}, {"id": 6080, "name": "89", "raw": "2023-07-31 07:35:10,031 | Failed at Play [01_deploy_vm] ******************************\n2023-07-31 07:35:10,031 | TASK [01_deploy_vm][Guest OS connection failure] ***********\ntask path: /home/worker/workspace/Ansible_Windows_11_MAIN_NVME_E1000E_EFI/ansible-vsphere-gos-validation/windows/utils/win_check_winrm.yml:26\nfatal: [localhost]: FAILED! => Guest winrm is not connectable in 1800 seconds.\nerror message:\nGuest winrm is not connectable in 1800 seconds.\n2023-07-31 07:35:47,031 | TASK [01_deploy_vm][Testing exit due to failure] ***********\ntask path: /home/worker/workspace/Ansible_Windows_11_MAIN_NVME_E1000E_EFI/ansible-vsphere-gos-validation/common/test_rescue.yml:86\nfatal: [localhost]: FAILED! => Exit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e\nerror message:\nExit testing because 'exit_testing_when_fail' is set to True in test case deploy_vm_efi_nvme_e1000e", "category": null, "processed": "timestamp failed at play number deploy vm timestamp task number deploy vm guest os connection failure task path home worker workspace ansible windows number main nvme efi ansible vsphere gos validation windows utilities win check win rm yml number fatal localhost failed guest win rm is not connectable in number seconds error message guest win rm is not connectable in number seconds timestamp task number deploy vm testing exit due to failure task path home worker workspace ansible windows number main nvme efi ansible vsphere gos validation common test rescue yml number fatal localhost failed exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e error message exit testing because exit testing when fail is set to true in test case deploy vm efi nvme e number e", "solution": "retry", "target": "testbed", "version": 202308030456}, {"id": 6084, "name": "89", "raw": "2023-07-31 09:41:56,031 | Failed at Play [1_paravirtual_vhba_device_ops] *************\n2023-07-31 09:41:56,031 | TASK [1_paravirtual_vhba_device_ops][Restart OS using win_reboot module] \ntask path: /home/worker/workspace/Ansible_Windows_11_70GA_LSILOGICSAS_E1000E_EFI/ansible-vsphere-gos-validation/windows/utils/win_shutdown_restart.yml:23\nTimeoutError: timed out\nThe above exception was the direct cause of the following exception:\nurllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.HTTPSConnection object at 0x7f409e1b2590>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)')\nThe above exception was the direct cause of the following exception:\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f409e1b2590>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nrequests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f409e1b2590>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nansible.errors.AnsibleError: HTTPSConnectionPool(host='10.168.211.149', port=5986): Max retries exceeded with url: /wsman (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7f409e1b2590>, 'Connection to 10.168.211.149 timed out. (connect timeout=5)'))\nException: Timed out waiting for last boot time check (timeout=600.0)\nfatal: [localhost -> 10.168.211.149]: FAILED! => Timed out waiting for last boot time check (timeout=600.0)\nerror message:\nTimed out waiting for last boot time check (timeout=600.0)", "category": null, "processed": "timestamp failed at play number para virtual v hba device ops timestamp task number para virtual v hba device ops restart os using win reboot module task path home worker workspace ansible windows number ga lsi logic sas efi ansible vsphere gos validation windows utilities win shutdown restart yml number timeout error timed out the above exception was the direct cause of the following exception url library number exceptions connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number the above exception was the direct cause of the following exception url library number exceptions max retry error https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number requests exceptions connect timeout https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number ansible errors ansible error https connection pool host ip address port number max retries exceeded with url wsman caused by connect timeout error url library number connection https connection object at hex id connection to ip address timed out connect timeout number exception timed out waiting for last boot time check timeout number fatal localhost ip address failed timed out waiting for last boot time check timeout number error message timed out waiting for last boot time check timeout number", "solution": "retry", "target": "targetvm", "version": 202308030456}]